Install apt-dists-merge explicitly (#27)
Without this fix, it causes the following LoadError:

    % rake -T
    rake aborted!
    LoadError: cannot load such file -- apt-dists-merge