Install apt-dists-merge
Without this fix, it causes the following LoadError:

  % rake -T
  rake aborted!
  LoadError: cannot load such file -- apt-dists-merge

Signed-off-by: Kentaro Hayashi <hayashi@clear-code.com>